<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>b_userName</name>
   <tag></tag>
   <elementGuidId>fc3d784a-4928-485f-80a7-0a7494322862</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[2]/div[2]/div[2]/table[1]/tbody[1]/tr[3]/td[1]/b[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(3) b</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'mohit 001' or . = 'mohit 001')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>b >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mohit 001</value>
      <webElementGuid>38d886da-198c-4b15-8112-caf82145b367</webElementGuid>
   </webElementProperties>
</WebElementEntity>
