<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>button_delete</name>
   <tag></tag>
   <elementGuidId>2f6cdc17-7623-4d56-92c6-1defb493d7f8</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[2]/div[2]/div[2]/table[1]/tbody[1]/tr[3]/td[4]/button[2]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(3) .btn-danger</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'btn-danger' and (text() = 'Delete' or . = 'Delete')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>button >> internal:text=&quot;Delete&quot;s >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-danger</value>
      <webElementGuid>38d886da-198c-4b15-8112-caf82145b367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>38d886da-198c-4b15-8112-caf82145b367</webElementGuid>
   </webElementProperties>
</WebElementEntity>
