<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>button_deleteUser</name>
   <tag></tag>
   <elementGuidId>2d4ede62-e187-4613-ad6b-d65d9f02a140</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[2]/div[2]/div[2]/table[1]/tbody[1]/tr[5]/td[4]/button[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@class,'btn-danger') and equals(@text,'Delete')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(5) .btn-danger</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(5) &gt; td:nth-child(4) &gt; .btn-danger</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-danger</value>
      <webElementGuid>ef52c673-61d0-4f25-8cf5-51825d053d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>ef52c673-61d0-4f25-8cf5-51825d053d32</webElementGuid>
   </webElementProperties>
</WebElementEntity>
