<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_toastSuccess</name>
   <tag></tag>
   <elementGuidId>56dacb56-d1fc-49a4-8f8b-272e639cfc35</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[4]/div[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.toast</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'toast success' and (text() = '✓User 123Mohit created' or . = '✓User 123Mohit created')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#toast-container div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toast success</value>
      <webElementGuid>a38aa01b-8287-4d9b-a587-c738f7a4dbfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>✓User 123Mohit created</value>
      <webElementGuid>a38aa01b-8287-4d9b-a587-c738f7a4dbfc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
