<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_userDeletedToast</name>
   <tag></tag>
   <elementGuidId>24f28ad4-8d47-450e-b599-6d38cb5566f1</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[4]/div[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.toast</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'toast error' and (text() = 'ℹ
         User deleted' or . = 'ℹ
         User deleted')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#toast-container div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toast error</value>
      <webElementGuid>38d886da-198c-4b15-8112-caf82145b367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ℹ
      User deleted</value>
      <webElementGuid>38d886da-198c-4b15-8112-caf82145b367</webElementGuid>
   </webElementProperties>
</WebElementEntity>
