<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>header_confirmAction</name>
   <tag></tag>
   <elementGuidId>76a51937-eaeb-48fb-9632-f70ceb85c048</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[3]/div[1]/div[1]/h3[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.modal-content > h3</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Confirm Action' or . = 'Confirm Action')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#modal-root h3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm Action</value>
      <webElementGuid>a38aa01b-8287-4d9b-a587-c738f7a4dbfc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
